# Generated by Django 3.2.4 on 2021-06-05 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_produtos_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem',
            name='itens',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Itens', to='core.item'),
            preserve_default=False,
        ),
    ]
